name = "test"
main = ".output/server/index.mjs"
compatibility_date = "2026-03-09"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "demo_test_db"
database_name = "demo-test-db"
database_id = "6217f83d-2684-4a15-ae1f-9561c92fcabb"

[assets]
binding = "ASSETS"
directory = ".output/public"

[[routes]]
pattern = "vibe-test.cogitations.com"
custom_domain = true
